/* fuzz_pio_asm.c — libFuzzer entry point for the PIO assembler.
 *
 * pio_asm_assemble parses untrusted text, so it is the most crash-prone
 * surface in the library: the tokenizer, the recursive-descent expression
 * evaluator, and the directive/label handling all run on arbitrary input.
 * This harness feeds fuzzer-generated bytes straight in, looking for crashes,
 * UB (UBSan) and memory errors (ASan). It asserts nothing about the result —
 * a rejected program is a valid outcome; only a crash is a bug.
 *
 * Build with clang: -fsanitize=fuzzer,address,undefined (see PIO_SIM_BUILD_FUZZERS).
 */

#include "pio_asm.h"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    /* pio_asm_assemble expects a NUL-terminated C string; give it its own
     * copy so ASan catches any read past the end. */
    char *src = (char *)malloc(size + 1U);
    if (src == NULL) {
        return 0;
    }
    memcpy(src, data, size);
    src[size] = '\0';

    pio_program_t prog;
    (void)pio_asm_assemble(src, NULL, &prog);

    /* Also exercise selecting a named program: use the input's own first line
     * as the name so the program-selection path sees fuzzed names too. A real
     * name is a single line, so terminate at the first newline (passing the
     * whole multi-line buffer would never match a `.program <name>`). */
    char name[64];
    size_t nlen = 0;
    while ((nlen < (sizeof(name) - 1U)) && (src[nlen] != '\0') && (src[nlen] != '\n')) {
        name[nlen] = src[nlen];
        nlen++;
    }
    name[nlen] = '\0';
    (void)pio_asm_assemble(src, name, &prog);

    free(src);
    return 0;
}
