/* test_pio_asm_vs_pioasm.c — encoding differential against the real pioasm.
 *
 * The in-tree pio_asm is otherwise only checked against hand-derived golden
 * encodings (test_pio_asm.c). This test removes that single point of trust: for
 * every program in the tests/pio corpus it assembles the source with pio_asm and
 * compares the resulting 16-bit instruction words — plus wrap targets and
 * side-set config — against the authoritative Raspberry Pi pioasm.
 *
 * pioasm runs at build time (CMake, when -DPIOASM_EXECUTABLE is set) and emits
 * one golden `<base>.json` per corpus file; this test reads that JSON and the
 * .pio source, so no subprocess or JSON library is needed at run time. The build
 * is gated to RP2350 (`pioasm -v 1`); base programs encode identically under v0.
 *
 * CORPUS[] (one basename per corpus file) is generated by CMake into
 * corpus_list.h. TESTS_PIO_DIR / PIOASM_JSON_DIR point at the sources and the
 * generated golden JSON.
 */

#include "unity.h"

#include "pio_asm.h"

#include "corpus_list.h"

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef TESTS_PIO_DIR
#error "TESTS_PIO_DIR must be defined (path to the .pio corpus)"
#endif
#ifndef PIOASM_JSON_DIR
#error "PIOASM_JSON_DIR must be defined (path to the generated golden JSON)"
#endif

void setUp(void) { (void)0; }
void tearDown(void) { (void)0; }

/* Slurp a whole file into a NUL-terminated heap buffer (caller frees). */
static char *read_file(const char *dir, const char *base, const char *ext)
{
    char path[1024];
    (void)snprintf(path, sizeof(path), "%s/%s%s", dir, base, ext);
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        return NULL;
    }
    (void)fseek(f, 0, SEEK_END);
    long n = ftell(f);
    (void)fseek(f, 0, SEEK_SET);
    if (n < 0) {
        (void)fclose(f);
        return NULL;
    }
    char *buf = malloc((size_t)n + 1U);
    if (buf == NULL) {
        (void)fclose(f);
        return NULL;
    }
    size_t got = fread(buf, 1, (size_t)n, f);
    buf[got] = '\0';
    (void)fclose(f);
    return buf;
}

/* One program parsed out of a pioasm JSON document. */
typedef struct {
    char name[64];
    uint16_t insns[PIO_ASM_MAX_INSNS];
    int count;
    int wrap_target;
    int wrap;
    int sideset_size;
    bool sideset_opt;
    bool sideset_pindirs;
    const char *next; /* scan cursor just past this program's name */
} json_program_t;

/* Read an integer that follows `"<key>":` starting at or after `from`, bounded
 * by `end`. Returns the value, or `dflt` if the key is absent before `end`. */
static int json_int_after(const char *from, const char *end, const char *key, int dflt)
{
    char pat[32];
    (void)snprintf(pat, sizeof(pat), "\"%s\"", key);
    const char *p = strstr(from, pat);
    if (p == NULL || p >= end) {
        return dflt;
    }
    p = strchr(p, ':');
    if (p == NULL || p >= end) {
        return dflt;
    }
    return (int)strtol(p + 1, NULL, 10);
}

/* True if `"<key>": true` appears between `from` and `end`. */
static bool json_bool_after(const char *from, const char *end, const char *key)
{
    char pat[32];
    (void)snprintf(pat, sizeof(pat), "\"%s\"", key);
    const char *p = strstr(from, pat);
    if (p == NULL || p >= end) {
        return false;
    }
    const char *t = strstr(p, "true");
    const char *f = strstr(p, "false");
    /* Whichever literal comes first after the colon wins (and must precede end). */
    if (t != NULL && t < end && (f == NULL || t < f)) {
        return true;
    }
    return false;
}

/* Find the next program object after `cursor` in a pioasm JSON document and fill
 * `out`. Returns false when no further program is present. */
static bool next_json_program(const char *cursor, json_program_t *out)
{
    const char *name = strstr(cursor, "\"name\"");
    if (name == NULL) {
        return false;
    }
    const char *q1 = strchr(name + 6, '"');
    if (q1 == NULL) {
        return false;
    }
    const char *q2 = strchr(q1 + 1, '"');
    if (q2 == NULL) {
        return false;
    }
    size_t len = (size_t)(q2 - (q1 + 1));
    if (len >= sizeof(out->name)) {
        len = sizeof(out->name) - 1U;
    }
    memcpy(out->name, q1 + 1, len);
    out->name[len] = '\0';
    out->next = q2 + 1;

    /* This program's fields live before the next program's "name" (or EOF). */
    const char *next_name = strstr(q2 + 1, "\"name\"");
    const char *end = (next_name != NULL) ? next_name : (cursor + strlen(cursor));

    out->wrap_target = json_int_after(q2, end, "wrapTarget", 0);
    out->wrap = json_int_after(q2, end, "wrap", 0);
    out->sideset_size = json_int_after(q2, end, "size", 0); /* inside "sideset" */
    out->sideset_opt = json_bool_after(q2, end, "optional");
    out->sideset_pindirs = json_bool_after(q2, end, "pindirs");

    /* Instruction words: every `"hex": "XXXX"` up to the next program. */
    out->count = 0;
    const char *p = strstr(q2, "\"instructions\"");
    if (p != NULL && p < end) {
        while (out->count < (int)PIO_ASM_MAX_INSNS) {
            const char *h = strstr(p, "\"hex\"");
            if (h == NULL || h >= end) {
                break;
            }
            const char *hq = strchr(h + 5, '"'); /* opening quote of the value */
            if (hq == NULL) {
                break;
            }
            out->insns[out->count] = (uint16_t)strtol(hq + 1, NULL, 16);
            out->count++;
            p = hq + 1;
        }
    }
    return true;
}

/* Cross-check one corpus basename: every program pioasm emitted must assemble to
 * the identical instruction words (and wrap/side-set) under pio_asm. */
static void check_corpus_file(const char *base)
{
    char *src = read_file(TESTS_PIO_DIR, base, ".pio");
    TEST_ASSERT_NOT_NULL_MESSAGE(src, base);
    char *json = read_file(PIOASM_JSON_DIR, base, ".json");
    TEST_ASSERT_NOT_NULL_MESSAGE(json, base);

    int programs = 0;
    const char *cursor = strstr(json, "\"programs\"");
    TEST_ASSERT_NOT_NULL_MESSAGE(cursor, base);

    json_program_t jp;
    while (next_json_program(cursor, &jp)) {
        cursor = jp.next;
        programs++;

        char msg[256];
        pio_program_t p;
        (void)snprintf(msg, sizeof(msg), "%s.pio: pio_asm rejected program '%s'", base, jp.name);
        TEST_ASSERT_TRUE_MESSAGE(pio_asm_assemble(src, jp.name, &p), msg);

        (void)snprintf(msg, sizeof(msg), "%s.pio:%s instruction count (pio_asm=%u pioasm=%d)", base,
                       jp.name, p.count, jp.count);
        TEST_ASSERT_EQUAL_INT_MESSAGE(jp.count, (int)p.count, msg);

        for (int i = 0; i < jp.count; i++) {
            (void)snprintf(msg, sizeof(msg), "%s.pio:%s[%d] pio_asm=0x%04X pioasm=0x%04X", base,
                           jp.name, i, p.insns[i], jp.insns[i]);
            TEST_ASSERT_EQUAL_HEX16_MESSAGE(jp.insns[i], p.insns[i], msg);
        }

        /* Wrap targets are program-relative instruction indices in both. */
        (void)snprintf(msg, sizeof(msg), "%s.pio:%s wrap_target", base, jp.name);
        TEST_ASSERT_EQUAL_INT_MESSAGE(jp.wrap_target, (int)p.wrap_bottom, msg);
        (void)snprintf(msg, sizeof(msg), "%s.pio:%s wrap", base, jp.name);
        TEST_ASSERT_EQUAL_INT_MESSAGE(jp.wrap, (int)p.wrap_top, msg);

        /* pioasm's side-set "size" already folds in the optional bit, matching
         * pio_asm's sideset_bits (data bits + opt). */
        (void)snprintf(msg, sizeof(msg), "%s.pio:%s sideset_bits", base, jp.name);
        TEST_ASSERT_EQUAL_INT_MESSAGE(jp.sideset_size, (int)p.sideset_bits, msg);
        (void)snprintf(msg, sizeof(msg), "%s.pio:%s sideset_opt", base, jp.name);
        TEST_ASSERT_EQUAL_INT_MESSAGE(jp.sideset_opt ? 1 : 0, p.sideset_opt ? 1 : 0, msg);
        (void)snprintf(msg, sizeof(msg), "%s.pio:%s sideset_pindirs", base, jp.name);
        TEST_ASSERT_EQUAL_INT_MESSAGE(jp.sideset_pindirs ? 1 : 0, p.sideset_pindirs ? 1 : 0, msg);
    }

    char msg[128];
    (void)snprintf(msg, sizeof(msg), "%s.pio: no programs found in golden JSON", base);
    TEST_ASSERT_GREATER_THAN_INT_MESSAGE(0, programs, msg);

    free(src);
    free(json);
}

static void test_corpus_encodings_match_pioasm(void)
{
    for (size_t i = 0; i < sizeof(CORPUS) / sizeof(CORPUS[0]); i++) {
        check_corpus_file(CORPUS[i]);
    }
}

int main(void)
{
    UNITY_BEGIN();
    RUN_TEST(test_corpus_encodings_match_pioasm);
    return UNITY_END();
}
